/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as HelpFaqRouteImport } from './routes/help.faq'
import { Route as HelpContactRouteImport } from './routes/help.contact'
import { Route as ApiTmdbSearchRouteImport } from './routes/api.tmdb.search'
import { Route as ApiTmdbPopularRouteImport } from './routes/api.tmdb.popular'
import { Route as AdminMoviesNewRouteImport } from './routes/admin.movies.new'
import { Route as AdminMoviesIdRouteImport } from './routes/admin.movies.$id'
import { Route as ApiTmdbMovieTmdbIdRouteImport } from './routes/api.tmdb.movie.$tmdbId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/help/contact',
  path: '/help/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbSearchRoute = ApiTmdbSearchRouteImport.update({
  id: '/api/tmdb/search',
  path: '/api/tmdb/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbPopularRoute = ApiTmdbPopularRouteImport.update({
  id: '/api/tmdb/popular',
  path: '/api/tmdb/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMoviesNewRoute = AdminMoviesNewRouteImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoviesIdRoute = AdminMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTmdbMovieTmdbIdRoute = ApiTmdbMovieTmdbIdRouteImport.update({
  id: '/api/tmdb/movie/$tmdbId',
  path: '/api/tmdb/movie/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/legal/terms': typeof LegalTermsRoute
  '/movie/$id': typeof MovieIdRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/movies/new': typeof AdminMoviesNewRoute
  '/api/tmdb/popular': typeof ApiTmdbPopularRoute
  '/api/tmdb/search': typeof ApiTmdbSearchRoute
  '/api/tmdb/movie/$tmdbId': typeof ApiTmdbMovieTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/legal/terms': typeof LegalTermsRoute
  '/movie/$id': typeof MovieIdRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/movies/new': typeof AdminMoviesNewRoute
  '/api/tmdb/popular': typeof ApiTmdbPopularRoute
  '/api/tmdb/search': typeof ApiTmdbSearchRoute
  '/api/tmdb/movie/$tmdbId': typeof ApiTmdbMovieTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/legal/terms': typeof LegalTermsRoute
  '/movie/$id': typeof MovieIdRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/movies/new': typeof AdminMoviesNewRoute
  '/api/tmdb/popular': typeof ApiTmdbPopularRoute
  '/api/tmdb/search': typeof ApiTmdbSearchRoute
  '/api/tmdb/movie/$tmdbId': typeof ApiTmdbMovieTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/plans'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/help/contact'
    | '/help/faq'
    | '/legal/terms'
    | '/movie/$id'
    | '/admin/movies/$id'
    | '/admin/movies/new'
    | '/api/tmdb/popular'
    | '/api/tmdb/search'
    | '/api/tmdb/movie/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/plans'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/help/contact'
    | '/help/faq'
    | '/legal/terms'
    | '/movie/$id'
    | '/admin/movies/$id'
    | '/admin/movies/new'
    | '/api/tmdb/popular'
    | '/api/tmdb/search'
    | '/api/tmdb/movie/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/plans'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/help/contact'
    | '/help/faq'
    | '/legal/terms'
    | '/movie/$id'
    | '/admin/movies/$id'
    | '/admin/movies/new'
    | '/api/tmdb/popular'
    | '/api/tmdb/search'
    | '/api/tmdb/movie/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  ProfilesRoute: typeof ProfilesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HelpContactRoute: typeof HelpContactRoute
  HelpFaqRoute: typeof HelpFaqRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MovieIdRoute: typeof MovieIdRoute
  ApiTmdbPopularRoute: typeof ApiTmdbPopularRoute
  ApiTmdbSearchRoute: typeof ApiTmdbSearchRoute
  ApiTmdbMovieTmdbIdRoute: typeof ApiTmdbMovieTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/help/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/search': {
      id: '/api/tmdb/search'
      path: '/api/tmdb/search'
      fullPath: '/api/tmdb/search'
      preLoaderRoute: typeof ApiTmdbSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/popular': {
      id: '/api/tmdb/popular'
      path: '/api/tmdb/popular'
      fullPath: '/api/tmdb/popular'
      preLoaderRoute: typeof ApiTmdbPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/movies/new': {
      id: '/admin/movies/new'
      path: '/movies/new'
      fullPath: '/admin/movies/new'
      preLoaderRoute: typeof AdminMoviesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movies/$id': {
      id: '/admin/movies/$id'
      path: '/movies/$id'
      fullPath: '/admin/movies/$id'
      preLoaderRoute: typeof AdminMoviesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/tmdb/movie/$tmdbId': {
      id: '/api/tmdb/movie/$tmdbId'
      path: '/api/tmdb/movie/$tmdbId'
      fullPath: '/api/tmdb/movie/$tmdbId'
      preLoaderRoute: typeof ApiTmdbMovieTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMoviesIdRoute: typeof AdminMoviesIdRoute
  AdminMoviesNewRoute: typeof AdminMoviesNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMoviesIdRoute: AdminMoviesIdRoute,
  AdminMoviesNewRoute: AdminMoviesNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  ProfilesRoute: ProfilesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HelpContactRoute: HelpContactRoute,
  HelpFaqRoute: HelpFaqRoute,
  LegalTermsRoute: LegalTermsRoute,
  MovieIdRoute: MovieIdRoute,
  ApiTmdbPopularRoute: ApiTmdbPopularRoute,
  ApiTmdbSearchRoute: ApiTmdbSearchRoute,
  ApiTmdbMovieTmdbIdRoute: ApiTmdbMovieTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
